# Generated by Django 3.2.9 on 2021-12-10 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awwardsApp', '0004_rename_image_project'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
